name: Update EPG
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  Update-epg:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2
        
      - name: update EPG
        run: cd epg && sh epg.sh

      - name: setup git config
        run: |
          git config user.name "M3UPT Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git status
          git add meo.pt.epg.xml meo.pt.epg.xml.gz
          git commit -m "Update EPG"
          git push origin main
