name: Update EPG (XMLTV)
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update-epg:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2
        
      - name: install xmltv
        run: sudo apt-get install -y xmltv
        
      - name: update EPG
        run: cd epg && sh epg_xmltv.sh

      - name: setup git config
        run: |
          git config user.name "M3UPT Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd epg
          git add meo-epg.xml meo-epg.xml.gz
          git commit -m "Update EPG"
          git push origin main
